language: node_js
node_js:
  - lts/*
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  name: $GITHUB_USERNAME
  keep-history: true
  fqdn: apuntes.majaja.org
  on:
    branch: master
